---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# rEcl

The goal of `rEcl` is to serve as a R wrapper of the class `EclBinaryParser`, written in Python, by [Konstantin Sermyagin](). The class converts the reservoir simulation output files generated by Eclipse from binary to dataframes.

## Installation
For the moment, `rEcl` is only available through Github. Once is completed it will be submitted to CRAN.


## Requirements

* R 3.5.3
* Rtools 3.5
* RStudio 1.2+. _I used RStudio preview 1.2.1327 for the development of the package._
* Python Anaconda3-2018.12-Windows-x86_64
* Conda environment 3.6 with pandas and numpy installed. _I called this environment_ `pyres`


## Files used for testing
For testing `rEcl` and `EclBinaryParser` I used the output binary files from the reservoir simulation of the Volve field.

```
VOLVE_2016.INIT
VOLVE_2016.RSSPEC
VOLVE_2016.SMSPEC
VOLVE_2016.UNSMRY
```

You can find a copy of these files in this repository under `rEcl/inst/python/volve` but the package will not install them. You will have to copy these files manually. In the future, I plan to download the files directly from Zenodo or Google drive, mainly, because these files are too big for an R package.



