static_props = ['DEPTH','DX','DR','DY','DTHETA','DZ','PORO','PERMX','PERMR',
'PERMI','PERMY','PERMTHT','PERMJ','PERMZ','PERMK','MULTX','MULTR','MULTI',
'MULTY','MULTTHT','MULTJ','MULTZ','MULTK','TRANX','TRANR','TRANI',
'TRANY','TRANTHT','TRANJ','TRANZ','TRANK','DIFFMX','DIFFMR','DIFFMI',
'DIFFMY','DIFFMTHT','DIFFMJ','DIFFMZ','DIFFMK','DIFFX','DIFFR',
'DIFFI','DIFFY','DIFFTHT','DIFFJ','DIFFZ','DIFFK','DIFFTX','DIFFTR',
'DIFFTI','DIFFTY','DIFFTTHT','DIFFTJ','DIFFTZ','DIFFTK','HEATTX',
'HEATTR','HEATTY','HEATTTHT','MLANGI','GASSATC','MLNGSLVI','MLANG',
'GASSATC','MLANGSLV','AQUIFERN','DOMAINS','ENDNUM','EQLNUM','FIPNUM','FLUXNUM',
'KRO','KRORW','KRW','KRWR','MINPVV','MULTNUM','MULTPV','MULTX','MULTX-',
'MULTY','MULTY-','MULTZ','MULTZ-','NTG','OPERNUM','PCW','PORV','PVTNUM',
'SATNUM','SOWCR','SWATINIT','SWCR','SWL','SWLPC','SWU','TOPS','TRANNNC']

